[Version]
  version = 0.1
  name = rank_model

[Categories]
 [[clinical_significance]]
   category_aggregation = sum

# [[variant_tier]]
#   category_aggregation = sum

# Category: clinical_significance

[reported]
  category = clinical_significance
  data_type = flag
  description = Variant is reported in the driver catalog
  field = INFO
  info_key = REPORTED

  [[reported]]
    score = 10

  [[not_reported]]
    score = 0

## Category: variant_tier
#
### String information has to have a 'priority' - but the order of clinical significance of each tier is unclear for now.
#
#[tier]
#  category = variant_tier
#  data_type = string
#  description = Tier of the variant according to the driver catalog
#  field = INFO
#  info_key = TIER
#  separators = ',',
#
#  [[hotspot]]
#    score = 10 # How does this tier overlap with the hotspot criteria?
#    string = HOTSPOT
#
#  [[panel]]
#    score = 10
#    string = PANEL
#
#  [[high_confidence]]
#    score = 10
#    string = HIGH_CONFIDENCE
#
#  [[low_confidence]]
#    score = -10
#    string = LOW_CONFIDENCE
#
#[hotspot]
#  category = variant_tier
#  data_type = flag
#  description = Site is at a known hotspot location
#  field = INFO
#  info_key = HOTSPOT
#
#  [[hotspot]]
#    score = 10
#
#  [[not_reported]]
#    score = 0
#
#[near_hotspot]
#  category = variant_tier
#  data_type = flag
#  description = Variant within 5 bases of hotspot
#  field = INFO
#  info_key = NEAR_HOTSPOT
#
#  [[near_hotspot]]
#    score = 5 # Variant near hotspot should have lower score than variant at hotspot
#
#  [[not_reported]]
#    score = 0
